### PR TITLE
Allow rendering all quest markers on minimap

### LINKED ISSUE #803: Show all quest log markers at once
Option to automatically cycle through quest log maybe on map change, grab quest indicator markers and plot on minimap to save having to cycle through all quests to find nearest one

### PR DESCRIPTION
**Pull request by adituv**
Adds an option to render all quest markers on the minimap rather than just the active quest

Closes #803

### CODE REVIEW

**Comment by 3vcloud** [comment]
Id be very surprised if this worked, the game doesn’t give you all quest information for every quest until you switch to it

**Comment by 3vcloud** [comment]
I think I added something in the info window to get all quest info, you’ll need to factor that in

**Comment by adituv** [comment]
It worked with my testing, but it was only with half a dozen quests in Plains of Jarin.  I'll have a further look.

**Comment by 3vcloud** [comment]
There’s a flag in the quest that tells you if it’s got all the data from the server or not, you can use that

**Comment by 3vcloud** [comment]
Do you even need to set as the active quest to get the marker info you need? Pretty sure that api call will sort it without messing with the users ui

**Comment by adituv** [comment]
It didn't, unfortunately.  The active quest method was because I didn't want to reverse engineer to find a new call, but a method that doesn't affect the user's UI would definitely be preferable.

Testing:
* I used the button in Info window to request quest info, markers did not show up.  flags = 0x1
* I set quest active manually in the quest log, marker showed up.  flags still = 0x1
* Repeated for several other quests, and markers appeared one by one on the minimap

**Comment by 3vcloud** [comment]
Ok we’ll hold this until I take another look at the quest code

**Comment by DubbleClick** [comment]
Into dev, please :)

**Comment by adituv** [comment]
Ah, I swear that never used to be an option!  I've closed and reopened PRs to be against a different branch so many times by now...

**Pull request merged**
