### PR TITLE
Add Special Cases for Map Travel

### PR DESCRIPTION
**Pull request by franneck94**
will search for more edge cases

### CODE REVIEW

**Comment by 3vcloud** [comment]
things like battledepths would be a good shout, the eotn layout is all over the place

**Comment by BearsMan** [comment]
@franneck94 If you would like me to, I can help find more locations for you and send you a list in a word document or something? I could even help with the code if needed? I know that finding every location can be tiresome and all.

**Comment by franneck94** [comment]
> @franneck94 If you would like me to, I can help find more locations for you and send you a list in a word document or something? I could even help with the code if needed? I know that finding every location can be tiresome and all.

Send me on discord the list

**Comment by franneck94** [comment]
> @franneck94 If you would like me to, I can help find more locations for you and send you a list in a word document or something? I could even help with the code if needed? I know that finding every location can be tiresome and all.

You can post the list here.

**Comment by BearsMan** [comment]
> > @franneck94 If you would like me to, I can help find more locations for you and send you a list in a Word document or something. I could even help with the code if needed. I know that finding every location can be tiresome and all.
> 
> You can post the list here.

Sure thing, I will post a list together for you.

**Comment by franneck94** [comment]
@BearsMan Have you already colected some examples?

**Comment by BearsMan** [comment]
> @BearsMan Have you already colected some examples?

@franneck94 I haven't been able to get around to it. I
Will try and get it done today. May I ask? Which cases do you need?

**Comment by BearsMan** [comment]
@franneck94 Which map ID cases are needed I am on the game now and can sort it if you would like me to.

**Comment by franneck94** [comment]
Regarding VQ i am done. I will maybe add a PR for Bountys in the future

**Comment by DubbleClick** [comment]
thanks

**Pull request merged**
