### PR TITLE
add lockpicks to pcons window

### PR DESCRIPTION
**Pull request by chypriote**
Lockpicks get regular use on almost every zone, think it makes sense to add them here

### CODE REVIEW

**Comment by 3vcloud** [comment]
Nope, you should instead make a hotkey to withdraw the item on map load for your use case. Whilst there are use cases for different types of summoning stones for certain speed clears, there’s no reason for lock picks to be added to the pcons window when there’s already a feature for withdrawing item by id

**Comment by adituv** [comment]
I don't see why lockpicks wouldn't fit here.  Couldn't speedclearers also use the "withdraw item by id" feature for their summoning stones?  Can the "withdraw item by id" feature maintain a minimum number of lockpicks on a character?  Particularly for poorer players who don't necessarily have a stack of lockpicks per character, I think this could be a useful addition

**Comment by DubbleClick** [comment]
This can be achieved with the /withdraw command too, so I agree that this isn't necessary. I'd even say that summoning stones have no business in the pcons window.

**Comment by 3vcloud** [comment]
Pcons are there primarily to be able to be turned on or off to automatically be used in an explorable- the autofill was added later as a nice to have, and has now also been separated out into the chat command for everything else. 

Everything currently in the pcons window is time sensitive to be renewed when it runs out in an explorable area, lock picks are not

**Comment by chypriote** [comment]
Think it's a sensitive way of deciding what to add or not to that window. Should I update this to remove the few items that should not be here then ? I'm thinking of stones, scrolls and morale pcons

**Comment by 3vcloud** [comment]
Maybe this isn’t worth the effort to argue, I think maybe we should just add this in with a view to being able to add more items like this through the ui in future? If it’s not enabled by default it’s not adding cruft for existing users

**Comment by chypriote** [comment]
I believe an UI similar to the one for hiding items from merchant would be the most fitting. Would you prefer closing that one and reopening a PR after I've implemented that ?

**Pull request merged**
