### PR TITLE
/pc results increased to 12 and party search text save between sessions

### PR DESCRIPTION
**Pull request by raben1**

### CODE REVIEW

**Comment by 3vcloud** [comment]
So I was thinking about this one - should the /pc command instead open the trade window with the search term instead? You’re expecting to engage with the content at that point so interrupting gameplay by showing a window wouldn't be a concern, and this way it doesn’t clog up the chat log

**Comment by raben1** [comment]
I find the /pc command really useful for a quick search, like in the middle of a run or waiting to fill the team, then you can open the trade window if you need a deeper search results. You can yet interact with the /pc results since the users are targetable to pm.

**Comment by DubbleClick** [comment]
wtf is the /pc command?

**Comment by BearsMan** [comment]
/pc if I am right, it means price check.

**Pull request merged**
