### PR TITLE
Enemy Window

### PR DESCRIPTION
**Pull request by backtwobaysix**
Its like a party window except for nearby enemies

### CODE REVIEW

**Comment by DubbleClick** [comment]
why close this? we've not found time to work on it yet because bug fixes over the reworks are more important, but we're generally happy to integrate it once we have a fully stable version released

**Comment by franneck94** [comment]
tried this some weeks ago and had random crashed while running through popping up enemies. but havnt looked into the reasons

**Comment by DubbleClick** [comment]
hence why it isn't merged.

I just don't have the time to dedicate integrating an entirely new window  when there are bugs and small things to take care of first

**Comment by backtwobaysix** [comment]
I closed it because I thought I was just being publicly left on read lol. I'm happy to implement improvements before merge but I cannot fix the skill name not displaying on latest version of tb/gwca, the crashes I will look at soon.

**Comment by DubbleClick** [comment]
merged in dev branch, will see release 6.22

**Pull request closed without merging**
